sequence <- 'GCGAACGGTTTTAGGGATTATTTATTTTTGTAGGTAAGGAGACGGAGGGTAGTTTTAGCGATTCGGATTTTAAGGAGTCGTTTTCGGAGGGTCGTTTCGACGCGTTGTAGGGTTTTTTTCGTATCGGCGGGTTTTTTTCGGTTGGGTTAGCGGCGGCGCGGTTGGCGGAGGATTCGGTTTTTTATTATTTCGTCGGAGCGTCGGCGTTCGGTTCGTATTTAGTCGCGGGCGAGGTGTTTTCGGGTTTCGGCGGGTTTTCGGTTATTTATTCGTCGTTTTCGTCGTCGTTTTTTGCGGTGTTCGTTAAGTTTAAATTGTGGTTTTTGGTAGAGATCGTTATATCGTCGGATAAGGTTAAGGACGGGGGCGGCGGGAACGAGGGTTTTTTATGTTTATCGTGTTTCGGGTTTATAGTCGGGTAAGTTTTAGGAGGTAGTCGGGCGTCGTCGGTTTCGGCGTCGTTACGTTCGTTTTCGGCGTAGTGTTTTTTTTTAGGCGGGACGGTGTTGTTTCGGTTTTTTTATTATATCGCGTTTTTTTATTTCGGTTATACGAATTATGGTTTTTTCGGATATTTTTATGGTTATTCGGGGTTCGGGTTAGGTTTTATAATCGGTTCGGGGTTTTATTTTAATGGATTAAATTAGATCGTGTTGAATCGAGCGGACGTTTTGGTTAAAGATTCGAAAATGTTGCGGAG'

# split the string two by two
# length of sequence
l <- nchar(sequence)
for (i in 1:(l-1)){
  if (substr(sequence, i, i + 1) == 'CG'){
    
    cat(i, "\n", sep = "")
    
  }
}